### ISSUE TITLE
使用在线接口时报错了

### ISSUE THREAD

**Issue by 133NSON** [rycbar77/LibcSearcher#1]
![image](https://user-images.githubusercontent.com/82507449/153169036-e813f23f-145f-462b-a54d-4fa2d7b44473.png)
师傅好，我这里本地搜libc可以用，但加上online=True时会出现这个报错。（之前可以在线搜也没问题，但一个月没有用之后就好像不行了）

**Comment by rycbar77** [comment]
应该是libc-database前两天服务器出的问题，试了一下现在已经好了

**Comment by 133NSON** [comment]
> 应该是libc-database前两天服务器出的问题，试了一下现在已经好了

好的，谢谢师傅
